local colors = {
  base = "#1e1e2e",
  mantle = "#181825",
  crust = "#11111b",
  surface0 = "#313244",
  surface1 = "#45475a",
  surface2 = "#585b70",
  text = "#cdd6f4",
  subtext1 = "#bac2de",
  subtext0 = "#a6adc8",
  overlay2 = "#9399b2",
  overlay1 = "#7f849c",
  overlay0 = "#6c7086",
  blue = "#89b4fa",
  lavender = "#b4befe",
  sapphire = "#74c7ec",
  sky = "#89dceb",
  teal = "#94e2d5",
  green = "#a6e3a1",
  yellow = "#f9e2af",
  peach = "#fab387",
  maroon = "#eba0ac",
  red = "#f38ba8",
  mauve = "#cba6f7",
  pink = "#f5c2e7",
  flamingo = "#f2cdcd",
  rosewater = "#f5e0dc",
}

return {
  normal = {
    a = { bg = colors.mauve, fg = colors.crust, gui = "bold" },
    b = { bg = colors.surface0, fg = colors.text },
    c = { bg = colors.base, fg = colors.subtext0 },
    z = { bg = colors.maroon, fg = colors.crust, gui = "bold" },
  },
  insert = {
    a = { bg = colors.blue, fg = colors.crust, gui = "bold" },
    b = { bg = colors.surface0, fg = colors.text },
    c = { bg = colors.base, fg = colors.subtext0 },
    z = { bg = colors.maroon, fg = colors.crust, gui = "bold" },
  },
  visual = {
    a = { bg = colors.peach, fg = colors.crust, gui = "bold" },
    b = { bg = colors.surface0, fg = colors.text },
    c = { bg = colors.base, fg = colors.subtext0 },
    z = { bg = colors.maroon, fg = colors.crust, gui = "bold" },
  },
  replace = {
    a = { bg = colors.red, fg = colors.crust, gui = "bold" },
    b = { bg = colors.surface0, fg = colors.text },
    c = { bg = colors.base, fg = colors.subtext0 },
    z = { bg = colors.maroon, fg = colors.crust, gui = "bold" },
  },
  command = {
    a = { bg = colors.green, fg = colors.crust, gui = "bold" },
    b = { bg = colors.surface0, fg = colors.text },
    c = { bg = colors.base, fg = colors.subtext0 },
    z = { bg = colors.maroon, fg = colors.crust, gui = "bold" },
  },
  inactive = {
    a = { bg = colors.base, fg = colors.overlay0, gui = "bold" },
    b = { bg = colors.base, fg = colors.overlay0 },
    c = { bg = colors.base, fg = colors.overlay0 },
  },
}
